#!/bin/sh
#SBATCH -J jordan_gc1
#SBATCH --output=/home/12297127/cls_thesis/cluster_output_files/pupilMaster.out 
#SBATCH --error=/home/12297127/cls_thesis/cluster_error_files/pupilMaster.err
#SBATCH --mail-user 12297127@student.uva.nl
#SBATCH --mail-type=ALL
#SBATCH --mem=64G
module load matlab {version 2017a}
matlab -nodisplay -r "addpath /home/12297127/cls_thesis/server_files/granger_cause/; gc_cluster.m; quit"
