#!/bin/sh
#SBATCH -J jae_gc_k_1_1
#SBATCH --output=/home/12297127/cls_thesis/cluster_output_files/jae_gc_k_1_1.out
#SBATCH --error=/home/12297127/cls_thesis/cluster_error_files/jae_gc_k_1_1.err
#SBATCH --mail-user 12297127@student.uva.nl
#SBATCH --mail-type=ALL
#SBATCH --mem=96G

module load matlab

matlab -nodisplay -r "addpath /home/12297127/cls_thesis/server_files/granger_cause/; kurt_granger_causality_1_vs_1; quit"
