#!/bin/sh
#SBATCH -J jae_p_mfgc1_one_vs_all
#SBATCH --output=/home/12297127/cls_thesis/cluster_output_files/pele_mf__one_vs_all.out
#SBATCH --error=/home/12297127/cls_thesis/cluster_error_files/pele_mf_one_vs_all.err
#SBATCH --mail-user 12297127@student.uva.nl
#SBATCH --mail-type=ALL
#SBATCH --mem=96G

module load matlab

matlab -nodisplay -r "addpath /home/12297127/cls_thesis/server_files/granger_cause/; pele_model_free_granger_causality_1_vs_all; quit"
